# Flowcase Installation Script for Windows
# This script automates the setup of Flowcase on Windows

# Set error handling
$ErrorActionPreference = "Continue"

# Simple output functions
function Write-Header($msg) {
    Write-Host ""
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host $msg -ForegroundColor Cyan
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host ""
}

function Write-Success($msg) {
    Write-Host "SUCCESS: $msg" -ForegroundColor Green
}

function Write-ErrorMsg($msg) {
    Write-Host "ERROR: $msg" -ForegroundColor Red
}

function Write-WarningMsg($msg) {
    Write-Host "WARNING: $msg" -ForegroundColor Yellow
}

function Write-InfoMsg($msg) {
    Write-Host "INFO: $msg" -ForegroundColor Cyan
}

# Start script
Write-Header "Flowcase Installation Script"

# Check prerequisites
Write-InfoMsg "Checking prerequisites..."

# Check Docker
Write-InfoMsg "Checking Docker..."
$dockerCheck = docker --version 2>&1
if ($LASTEXITCODE -eq 0) {
    Write-Success "Docker is installed: $dockerCheck"
} else {
    Write-ErrorMsg "Docker is not installed. Please install Docker Desktop first."
    Write-InfoMsg "Visit: https://www.docker.com/products/docker-desktop"
    exit 1
}

# Check Docker Compose
Write-InfoMsg "Checking Docker Compose..."
$composeCheck = docker compose version 2>&1
if ($LASTEXITCODE -eq 0) {
    Write-Success "Docker Compose is installed: $composeCheck"
} else {
    Write-ErrorMsg "Docker Compose is not installed or not working."
    exit 1
}

# Check if Docker daemon is running
Write-InfoMsg "Checking Docker daemon..."
$dockerInfo = docker info 2>&1
if ($LASTEXITCODE -eq 0) {
    Write-Success "Docker daemon is running"
} else {
    Write-ErrorMsg "Docker daemon is not running. Please start Docker Desktop."
    exit 1
}

# Check if .env already exists
if (Test-Path .env) {
    Write-WarningMsg ".env file already exists"
    $overwrite = Read-Host "Do you want to overwrite it? (y/N)"
    if ($overwrite -ne "y" -and $overwrite -ne "Y") {
        Write-InfoMsg "Keeping existing .env file"
        $script:skipEnv = $true
    } else {
        Write-InfoMsg "Backing up existing .env to .env.backup"
        Copy-Item .env .env.backup -ErrorAction SilentlyContinue
    }
}

# Generate random passwords - compatible method
function Generate-Password {
    $length = 24
    $chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    $random = New-Object System.Random
    $password = ""
    for ($i = 0; $i -lt $length; $i++) {
        $password += $chars[$random.Next(0, $chars.Length)]
    }
    return $password
}

function Generate-SecretKey {
    $length = 50
    $chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    $random = New-Object System.Random
    $key = ""
    for ($i = 0; $i -lt $length; $i++) {
        $key += $chars[$random.Next(0, $chars.Length)]
    }
    return $key
}

# Configuration
Write-Header "Configuration"

# Domain
$domain = Read-Host "Enter your domain (default: localhost)"
if ([string]::IsNullOrWhiteSpace($domain)) {
    $domain = "localhost"
}
Write-InfoMsg "Domain: $domain"

# Admin Email
$adminEmail = Read-Host "Enter admin email for Let's Encrypt (default: admin@example.com)"
if ([string]::IsNullOrWhiteSpace($adminEmail)) {
    $adminEmail = "admin@example.com"
}
Write-InfoMsg "Admin Email: $adminEmail"

# CA Server
if ($domain -eq "localhost") {
    $caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
    Write-InfoMsg "Using Let's Encrypt staging (for localhost)"
} else {
    $useProduction = Read-Host "Use Let's Encrypt production? (Y/n)"
    if ($useProduction -eq "n" -or $useProduction -eq "N") {
        $caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
        Write-InfoMsg "Using Let's Encrypt staging"
    } else {
        $caServer = "https://acme-v02.api.letsencrypt.org/directory"
        Write-InfoMsg "Using Let's Encrypt production"
    }
}

# Generate passwords
Write-InfoMsg "Generating secure passwords..."
$pgPass = Generate-Password
$authentikSecretKey = Generate-SecretKey

# Create .env file
if (-not $script:skipEnv) {
    Write-InfoMsg "Creating .env file..."
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $envContent = "# Flowcase Environment Variables`n"
    $envContent += "# Generated by install.ps1 on $timestamp`n"
    $envContent += "`n"
    $envContent += "# Domain Configuration`n"
    $envContent += "DOMAIN=$domain`n"
    $envContent += "`n"
    $envContent += "# Traefik Configuration`n"
    $envContent += "ADMIN_EMAIL=$adminEmail`n"
    $envContent += "CA_SERVER=$caServer`n"
    $envContent += "`n"
    $envContent += "# PostgreSQL Configuration`n"
    $envContent += "PG_PASS=$pgPass`n"
    $envContent += "`n"
    $envContent += "# Authentik Configuration`n"
    $envContent += "AUTHENTIK_SECRET_KEY=$authentikSecretKey`n"
    
    [System.IO.File]::WriteAllText("$PWD\.env", $envContent, [System.Text.Encoding]::UTF8)
    Write-Success ".env file created"
}

# Display credentials
Write-Header "Generated Credentials"
Write-Host "PostgreSQL Password: $pgPass"
Write-Host "Authentik Secret Key: $authentikSecretKey"
Write-Host ""
Write-WarningMsg "Save these credentials securely!"
Write-Host ""

# Ask about Authentik
$enableAuthentik = Read-Host "Do you want to enable Authentik authentication? (y/N)"
if ($enableAuthentik -eq "y" -or $enableAuthentik -eq "Y") {
    Write-InfoMsg "Authentik will be enabled after initial setup"
} else {
    Write-InfoMsg "Authentik middleware is disabled (you can enable it later)"
}

# Start services
Write-Header "Starting Flowcase"
Write-InfoMsg "This may take a few minutes on first run..."

docker compose up -d
if ($LASTEXITCODE -eq 0) {
    Write-Success "Containers started"
} else {
    Write-ErrorMsg "Failed to start containers"
    exit 1
}

# Wait for services to be ready
Write-InfoMsg "Waiting for services to be ready..."
Start-Sleep -Seconds 10

# Check service status
Write-Header "Service Status"
docker compose ps

# Display access information
Write-Header "Installation Complete!"
Write-Host ""
Write-Success "Flowcase is now running!"
Write-Host ""
Write-Host "Access Information:"
Write-Host "  - Flowcase: http://$domain or https://$domain"
if ($enableAuthentik -eq "y" -or $enableAuthentik -eq "Y") {
    Write-Host "  - Authentik Admin: https://authentik.$domain"
}
Write-Host ""
Write-InfoMsg "Default admin credentials will be displayed in the logs."
Write-InfoMsg "View logs with: docker compose logs -f"
Write-Host ""
Write-WarningMsg "Look for the default admin username and password in the logs!"
Write-Host ""
Write-InfoMsg "To view logs: docker compose logs -f"
Write-InfoMsg "To stop: docker compose down"
Write-InfoMsg "To restart: docker compose restart"
Write-Host ""
Write-InfoMsg "For detailed setup instructions, see SETUP.md"
Write-Host ""

# Show logs for credentials
Write-InfoMsg "Showing recent logs (look for default credentials)..."
Write-Host ""
Start-Sleep -Seconds 2
docker compose logs --tail=50 web 2>&1 | Select-String -Pattern "Created default users" -Context 0,10
Write-Host ""

if ($enableAuthentik -eq "y" -or $enableAuthentik -eq "Y") {
    Write-InfoMsg "Next steps:"
    Write-Host "1. Access Authentik at https://authentik.$domain"
    Write-Host "2. Follow the Authentik setup guide in SETUP.md"
    Write-Host "3. Enable Authentik middleware in docker-compose.yml"
}

Write-Success "Installation complete!"
