#!/bin/bash

# Flowcase Installation Script
# This script automates the setup of Flowcase

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Functions
print_header() {
    echo -e "${BLUE}========================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}========================================${NC}"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ $1${NC}"
}

# Check if running as root
if [ "$EUID" -eq 0 ]; then 
    print_warning "It's recommended to run this script as a non-root user with docker permissions"
    read -p "Continue anyway? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

print_header "Flowcase Installation Script"

# Check prerequisites
print_info "Checking prerequisites..."

# Check Docker
if ! command -v docker &> /dev/null; then
    print_error "Docker is not installed. Please install Docker first."
    echo "Visit: https://www.docker.com/get-started"
    exit 1
fi
print_success "Docker is installed"

# Check Docker Compose
if ! docker compose version &> /dev/null; then
    print_error "Docker Compose is not installed or not working."
    exit 1
fi
print_success "Docker Compose is installed"

# Check if Docker daemon is running
if ! docker info &> /dev/null; then
    print_error "Docker daemon is not running. Please start Docker."
    exit 1
fi
print_success "Docker daemon is running"

# Check if .env already exists
if [ -f .env ]; then
    print_warning ".env file already exists"
    read -p "Do you want to overwrite it? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        print_info "Keeping existing .env file"
        SKIP_ENV=true
    else
        print_info "Backing up existing .env to .env.backup"
        cp .env .env.backup
    fi
fi

# Generate random passwords
generate_password() {
    openssl rand -base64 24 | tr -d "=+/" | cut -c1-24
}

generate_secret_key() {
    openssl rand -base64 32 | tr -d "=+/" | cut -c1-50
}

# Configuration
print_header "Configuration"

# Domain
read -p "Enter your domain (default: localhost): " DOMAIN
DOMAIN=${DOMAIN:-localhost}
print_info "Domain: $DOMAIN"

# Admin Email
read -p "Enter admin email for Let's Encrypt (default: admin@example.com): " ADMIN_EMAIL
ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
print_info "Admin Email: $ADMIN_EMAIL"

# CA Server
if [ "$DOMAIN" = "localhost" ]; then
    CA_SERVER="https://acme-staging-v02.api.letsencrypt.org/directory"
    print_info "Using Let's Encrypt staging (for localhost)"
else
    read -p "Use Let's Encrypt production? (Y/n): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Nn]$ ]]; then
        CA_SERVER="https://acme-staging-v02.api.letsencrypt.org/directory"
        print_info "Using Let's Encrypt staging"
    else
        CA_SERVER="https://acme-v02.api.letsencrypt.org/directory"
        print_info "Using Let's Encrypt production"
    fi
fi

# Generate passwords
print_info "Generating secure passwords..."
PG_PASS=$(generate_password)
AUTHENTIK_SECRET_KEY=$(generate_secret_key)

# Create .env file
if [ "$SKIP_ENV" != "true" ]; then
    print_info "Creating .env file..."
    cat > .env << EOF
# Flowcase Environment Variables
# Generated by install.sh on $(date)

# Domain Configuration
DOMAIN=$DOMAIN

# Traefik Configuration
ADMIN_EMAIL=$ADMIN_EMAIL
CA_SERVER=$CA_SERVER

# PostgreSQL Configuration
PG_PASS=$PG_PASS

# Authentik Configuration
AUTHENTIK_SECRET_KEY=$AUTHENTIK_SECRET_KEY
EOF
    print_success ".env file created"
fi

# Display credentials
print_header "Generated Credentials"
echo "PostgreSQL Password: $PG_PASS"
echo "Authentik Secret Key: $AUTHENTIK_SECRET_KEY"
echo ""
print_warning "Save these credentials securely!"
echo ""

# Ask about Authentik
read -p "Do you want to enable Authentik authentication? (y/N): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    ENABLE_AUTHENTIK=true
    print_info "Authentik will be enabled after initial setup"
else
    ENABLE_AUTHENTIK=false
    print_info "Authentik middleware is disabled (you can enable it later)"
fi

# Start services
print_header "Starting Flowcase"
print_info "This may take a few minutes on first run..."

docker compose up -d

print_success "Containers started"

# Wait for services to be ready
print_info "Waiting for services to be ready..."
sleep 10

# Check service status
print_header "Service Status"
docker compose ps

# Display access information
print_header "Installation Complete!"
echo ""
print_success "Flowcase is now running!"
echo ""
echo "Access Information:"
echo "  - Flowcase: http://$DOMAIN or https://$DOMAIN"
if [ "$ENABLE_AUTHENTIK" = "true" ]; then
    echo "  - Authentik Admin: https://authentik.$DOMAIN"
fi
echo ""
print_info "Default admin credentials will be displayed in the logs."
echo "View logs with: docker compose logs -f"
echo ""
print_warning "Look for the default admin username and password in the logs!"
echo ""
print_info "To view logs: docker compose logs -f"
print_info "To stop: docker compose down"
print_info "To restart: docker compose restart"
echo ""
print_info "For detailed setup instructions, see SETUP.md"
echo ""

# Show logs for a few seconds to catch credentials
print_info "Showing recent logs (look for default credentials)..."
echo ""
docker compose logs --tail=50 web | grep -A 10 "Created default users" || true
echo ""

if [ "$ENABLE_AUTHENTIK" = "true" ]; then
    print_info "Next steps:"
    echo "1. Access Authentik at https://authentik.$DOMAIN"
    echo "2. Follow the Authentik setup guide in SETUP.md"
    echo "3. Enable Authentik middleware in docker-compose.yml"
fi

print_success "Installation complete! 🎉"

